# Generated by Django 3.2.6 on 2021-09-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='release_date',
            field=models.DateField(default='2016-07-15'),
            preserve_default=False,
        ),
    ]
